/// <reference types="vite/client" />

declare namespace JSX {
  interface IntrinsicElements {
    "model-viewer": React.DetailedHTMLProps<React.AllHTMLAttributes<HTMLElement>, HTMLElement> & {
      src: string;
      alt?: string;
      "auto-rotate"?: boolean;
      "camera-controls"?: boolean;
      "ar"?: boolean;
      "ar-modes"?: string;
      "shadow-intensity"?: string;
      "camera-orbit"?: string;
      "field-of-view"?: string;
      "min-field-of-view"?: string;
      "max-field-of-view"?: string;
      "exposure"?: string;
      "skybox-image"?: string;
      "environment-image"?: string;
      "poster"?: string;
      "loading"?: "eager" | "lazy";
      "reveal"?: "auto" | "interaction" | "manual";
      "interaction-prompt"?: "auto" | "none" | "legacy";
      "interaction-prompt-threshold"?: string;
      "interaction-prompt-style"?: "basic" | "wiggle";
      "interaction-prompt-variant"?: "ring" | "dot" | "reticle";
      "disable-zoom"?: boolean;
      "disable-pan"?: boolean;
      "disable-rotate"?: boolean;
      "rotation-per-second"?: string;
      "max-camera-orbit"?: string;
      "min-camera-orbit"?: string;
      "max-field-of-view-deg"?: string;
      "min-field-of-view-deg"?: string;
      "max-camera-pitch"?: string;
      "min-camera-pitch"?: string;
      "max-camera-roll"?: string;
      "min-camera-roll"?: string;
      "max-camera-azimuth"?: string;
      "min-camera-azimuth"?: string;
      "camera-target"?: string;
      "animation-name"?: string;
      "animation-crossfade-duration"?: string;
      "variant-name"?: string;
      "orientation"?: string;
      "scale"?: string;
      "autoplay"?: boolean;
      "seamless-poster"?: boolean;
      "interpolation-decay"?: string;
      "shadow-softness"?: string;
      "tone-mapping"?: string;
      "unbounded-orbits"?: boolean;
      "ar-scale"?: "auto" | "fixed";
      "ar-placement"?: "floor" | "wall";
      "ar-modes"?: string;
      "ar-status"?: string;
      "ar-fallback-url"?: string;
      "ar-button"?: string;
      "ar-button-text"?: string;
      "ar-button-alt"?: string;
      "ar-button-class"?: string;
      "ar-button-id"?: string;
      "ar-button-slot"?: string;
      "ar-button-style"?: string;
      "ar-button-tabindex"?: string;
      "ar-button-title"?: string;
      "ar-button-aria-label"?: string;
      "ar-button-aria-hidden"?: string;
      "ar-button-aria-live"?: string;
      "ar-button-aria-atomic"?: string;
      "ar-button-aria-relevant"?: string;
      "ar-button-role"?: string;
      "ar-button-src"?: string;
      "ar-button-alt-src"?: string;
      "ar-button-icon"?: string;
      "ar-button-icon-alt"?: string;
      "ar-button-icon-class"?: string;
      "ar-button-icon-id"?: string;
      "ar-button-icon-slot"?: string;
      "ar-button-icon-style"?: string;
      "ar-button-icon-tabindex"?: string;
      "ar-button-icon-title"?: string;
      "ar-button-icon-aria-label"?: string;
      "ar-button-icon-aria-hidden"?: string;
      "ar-button-icon-aria-live"?: string;
      "ar-button-icon-aria-atomic"?: string;
      "ar-button-icon-aria-relevant"?: string;
      "ar-button-icon-role"?: string;
      "ar-button-icon-src"?: string;
      "ar-button-icon-alt-src"?: string;
      "ar-button-icon-width"?: string;
      "ar-button-icon-height"?: string;
      "ar-button-icon-viewbox"?: string;
      "ar-button-icon-fill"?: string;
      "ar-button-icon-stroke"?: string;
      "ar-button-icon-stroke-width"?: string;
      "ar-button-icon-stroke-linecap"?: string;
      "ar-button-icon-stroke-linejoin"?: string;
      "ar-button-icon-transform"?: string;
      "ar-button-icon-transform-origin"?: string;
      "ar-button-icon-transform-box"?: string;
      "ar-button-icon-transform-matrix"?: string;
      "ar-button-icon-transform-translate"?: string;
      "ar-button-icon-transform-rotate"?: string;
      "ar-button-icon-transform-scale"?: string;
      "ar-button-icon-transform-skewx"?: string;
      "ar-button-icon-transform-skewy"?: string;
      "ar-button-icon-transform-origin-x"?: string;
      "ar-button-icon-transform-origin-y"?: string;
      "ar-button-icon-transform-origin-z"?: string;
      "ar-button-icon-transform-box-x"?: string;
      "ar-button-icon-transform-box-y"?: string;
      "ar-button-icon-transform-box-z"?: string;
      "ar-button-icon-transform-matrix-a"?: string;
      "ar-button-icon-transform-matrix-b"?: string;
      "ar-button-icon-transform-matrix-c"?: string;
      "ar-button-icon-transform-matrix-d"?: string;
      "ar-button-icon-transform-matrix-e"?: string;
      "ar-button-icon-transform-matrix-f"?: string;
      "ar-button-icon-transform-translate-x"?: string;
      "ar-button-icon-transform-translate-y"?: string;
      "ar-button-icon-transform-rotate-angle"?: string;
      "ar-button-icon-transform-rotate-x"?: string;
      "ar-button-icon-transform-rotate-y"?: string;
      "ar-button-icon-transform-rotate-z"?: string;
      "ar-button-icon-transform-scale-x"?: string;
      "ar-button-icon-transform-scale-y"?: string;
      "ar-button-icon-transform-skewx-angle"?: string;
      "ar-button-icon-transform-skewy-angle"?: string;
      "ar-button-icon-transform-origin-x-unit"?: string;
      "ar-button-icon-transform-origin-y-unit"?: string;
      "ar-button-icon-transform-origin-z-unit"?: string;
      "ar-button-icon-transform-box-x-unit"?: string;
      "ar-button-icon-transform-box-y-unit"?: string;
      "ar-button-icon-transform-box-z-unit"?: string;
      "ar-button-icon-transform-matrix-a-unit"?: string;
      "ar-button-icon-transform-matrix-b-unit"?: string;
      "ar-button-icon-transform-matrix-c-unit"?: string;
      "ar-button-icon-transform-matrix-d-unit"?: string;
      "ar-button-icon-transform-matrix-e-unit"?: string;
      "ar-button-icon-transform-matrix-f-unit"?: string;
      "ar-button-icon-transform-translate-x-unit"?: string;
      "ar-button-icon-transform-translate-y-unit"?: string;
      "ar-button-icon-transform-rotate-angle-unit"?: string;
      "ar-button-icon-transform-rotate-x-unit"?: string;
      "ar-button-icon-transform-rotate-y-unit"?: string;
      "ar-button-icon-transform-rotate-z-unit"?: string;
      "ar-button-icon-transform-scale-x-unit"?: string;
      "ar-button-icon-transform-scale-y-unit"?: string;
      "ar-button-icon-transform-skewx-angle-unit"?: string;
      "ar-button-icon-transform-skewy-angle-unit"?: string;
    };
  }
}